{
  "step-durations": {
    "CheckoutBuild": 0,
    "": 0,
    "ComputeClasspath": 4,
    "CloneRepository": 5,
    "BuildProject": 777,
    "PushIncriminatedBuild": 5,
    "SquashRepository": 3
  },
  "buildid": 221925815,
  "workspace": "./workspace",
  "repo": "javaee-samples/javaee7-samples",
  "error-types": [
    "com.sun.jersey.api.container.ContainerException"
  ],
  "failing-test-cases": [
    {
      "className": "org.javaee7.batch.chunk.csv.database.BatchCSVDatabaseTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.javaee7.batch.chunk.csv.database.BatchCSVDatabaseTest#org.javaee7.batch.chunk.csv.database.BatchCSVDatabaseTest"
      ],
      "failures": [
        {
          "failureName": "com.sun.jersey.api.container.ContainerException",
          "failureDetail": "exit_code: FAILURE, message: Error occurred during deployment: Exception while preparing the app : Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.4.qualifier): org.eclipse.persistence.exceptions.DatabaseException Internal Exception: java.sql.SQLException: Error in allocating a connection. Cause: Connection could not be allocated because: java.net.ConnectException : Error connecting to server localhost on port 1527 with message Connection refused (Connection refused). Error Code: 0. Please see server.log for more details. [status: CLIENT_ERROR reason: Bad Request]",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 1
    }
  ],
  "failingModule": "/root/workspace/javaee-samples/javaee7-samples/221925815/batch/chunk-csv-database"
}