#Repairnator properties
#Thu Mar 30 17:48:53 CEST 2017
step-durations=[CheckoutBuild\=3, \=1, CloneRepository\=21]
workspace=./workspace
pr-remote-repo=jihoonson/druid
pr-head-commit-id=8b64ce6ec9e083632bce7bf9fcc365b1d857a41b
pr-id=4134
repo=druid-io/druid
failingModule=/root/workspace/druid-io/druid/216695950/server
is-pr=true
buildid=216695950
error-types=java.lang.AssertionError
failing-test-cases=FailureLocation{className\='io.druid.segment.loading.SegmentLoaderLocalCacheManagerTest', failingMethods\=[io.druid.segment.loading.SegmentLoaderLocalCacheManagerTest\#testRetryAllFail, io.druid.segment.loading.SegmentLoaderLocalCacheManagerTest\#testRetrySuccessAtSecondLocation], erroringMethods\=[], failures\=[FailureType{failureName\='java.lang.AssertionError', failureDetail\='null', isError\=false}, FailureType{failureName\='java.lang.AssertionError', failureDetail\='null', isError\=false}], nbFailures\=2, nbErrors\=0},FailureLocation{className\='io.druid.segment.loading.LocalDataSegmentPusherTest', failingMethods\=[io.druid.segment.loading.LocalDataSegmentPusherTest\#testPushCannotCreateDirectory], erroringMethods\=[], failures\=[FailureType{failureName\='java.lang.AssertionError', failureDetail\='Expected test to throw (an instance of java.io.IOException and exception with message a string containing "Unable to create directory")', isError\=false}], nbFailures\=1, nbErrors\=0},FailureLocation{className\='io.druid.query.lookup.LookupSnapshotTakerTest', failingMethods\=[io.druid.query.lookup.LookupSnapshotTakerTest\#testIOExceptionDuringLookupPersist], erroringMethods\=[], failures\=[FailureType{failureName\='java.lang.AssertionError', failureDetail\='Expected exception\: io.druid.java.util.common.ISE', isError\=false}], nbFailures\=1, nbErrors\=0}
pr-base-commit-id=801ea5efa423513133c742d2b1b6875a18d1b8e9
