#Repairnator properties
#Sun Mar 26 04:44:44 CEST 2017
step-durations=[CheckoutBuild\=2, \=0, CloneRepository\=38]
workspace=./workspace
pr-remote-repo=p6spy/p6spy
pr-head-commit-id=0c79ec7507af5ee332d1ce7a28f5fa0df237094e
pr-id=375
repo=p6spy/p6spy
failingModule=/root/workspace/p6spy/p6spy/215098301
is-pr=true
buildid=215098301
error-types=java.lang.AssertionError\:,bitronix.tm.resource.ResourceConfigurationException
failing-test-cases=FailureLocation{className\='com.p6spy.engine.spy.P6TestCallableStatement', failingMethods\=[com.p6spy.engine.spy.P6TestCallableStatement\#binaryExcludedFalse[0\: HSQLDB], com.p6spy.engine.spy.P6TestCallableStatement\#binaryExcludedTrue[0\: HSQLDB]], erroringMethods\=[], failures\=[FailureType{failureName\='java.lang.AssertionError\:', failureDetail\='null', isError\=false}, FailureType{failureName\='java.lang.AssertionError\:', failureDetail\='null', isError\=false}], nbFailures\=2, nbErrors\=0},FailureLocation{className\='com.p6spy.engine.spy.XADataSourceTest', failingMethods\=[], erroringMethods\=[com.p6spy.engine.spy.XADataSourceTest\#twoPhaseCommitDataPersistedOnCommit[0\: H2], com.p6spy.engine.spy.XADataSourceTest\#twoPhaseCommitDataNotPersistedOnRollback[0\: H2]], failures\=[FailureType{failureName\='bitronix.tm.resource.ResourceConfigurationException', failureDetail\='cannot create JDBC datasource named jdbc/inTestDs', isError\=true}, FailureType{failureName\='bitronix.tm.resource.ResourceConfigurationException', failureDetail\='cannot create JDBC datasource named jdbc/inTestDs', isError\=true}], nbFailures\=0, nbErrors\=2}
pr-base-commit-id=e4c87815f2c41f62dcfee85558a0f4a3b0ef9f0e
