#Repairnator properties
#Sun Mar 26 04:41:40 CEST 2017
step-durations=[CheckoutBuild\=0, \=0, ComputeClasspath\=12, CloneRepository\=38, NopolRepair\=23, PushIncriminatedBuild\=4, ComputeSourceDir\=0, SquashRepository\=5]
buildid=215097977
workspace=./workspace
repo=p6spy/p6spy
error-types=java.lang.AssertionError\:,bitronix.tm.resource.ResourceConfigurationException
failing-test-cases=FailureLocation{className\='com.p6spy.engine.spy.P6TestCallableStatement', failingMethods\=[com.p6spy.engine.spy.P6TestCallableStatement\#binaryExcludedFalse[0\: HSQLDB], com.p6spy.engine.spy.P6TestCallableStatement\#binaryExcludedTrue[0\: HSQLDB]], erroringMethods\=[], failures\=[FailureType{failureName\='java.lang.AssertionError\:', failureDetail\='null', isError\=false}, FailureType{failureName\='java.lang.AssertionError\:', failureDetail\='null', isError\=false}], nbFailures\=2, nbErrors\=0},FailureLocation{className\='com.p6spy.engine.spy.XADataSourceTest', failingMethods\=[], erroringMethods\=[com.p6spy.engine.spy.XADataSourceTest\#twoPhaseCommitDataPersistedOnCommit[0\: H2], com.p6spy.engine.spy.XADataSourceTest\#twoPhaseCommitDataNotPersistedOnRollback[0\: H2]], failures\=[FailureType{failureName\='bitronix.tm.resource.ResourceConfigurationException', failureDetail\='cannot create JDBC datasource named jdbc/inTestDs', isError\=true}, FailureType{failureName\='bitronix.tm.resource.ResourceConfigurationException', failureDetail\='cannot create JDBC datasource named jdbc/inTestDs', isError\=true}], nbFailures\=0, nbErrors\=2}
failingModule=/root/workspace/p6spy/p6spy/215097977
