{
  "pr-base-commit-id": "2958cc22a6a00609bfbb6eb17d4e401dfe433123",
  "pr-head-commit-id": "3e0e45bdae2ba150ef6649e5b8753bece60b652e",
  "totalNumberSkippingTests": 1,
  "pr-remote-repo": "vlsi/pgjdbc",
  "error-types": [
    "org.postgresql.util.PSQLException",
    "java.lang.NullPointerException:",
    "skipped"
  ],
  "totalNumberFailingTests": 0,
  "buildid": 222601706,
  "totalNumberErroringTests": 390,
  "is-pr": "true",
  "totalNumberRunningTests": 427,
  "pr-head-commit-id-url": "https://github.com/vlsi/pgjdbc/commit/3e0e45bdae2ba150ef6649e5b8753bece60b652e",
  "pr-id": 814,
  "repo": "pgjdbc/pgjdbc",
  "failing-test-cases": [
    {
      "className": "org.postgresql.test.jdbc4.Jdbc4TestSuite",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc4.Jdbc4TestSuite#initializationError"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 1
    },
    {
      "className": "org.postgresql.test.jdbc42.GetObject310Test",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc42.GetObject310Test#testGetLocalTimeInvalidType",
        "org.postgresql.test.jdbc42.GetObject310Test#testGetLocalTimeNull",
        "org.postgresql.test.jdbc42.GetObject310Test#testGetLocalDateTime",
        "org.postgresql.test.jdbc42.GetObject310Test#testGetLocalTime",
        "org.postgresql.test.jdbc42.GetObject310Test#testGetTimestampWithTimeZone",
        "org.postgresql.test.jdbc42.GetObject310Test#testGetLocalDate"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 6
    },
    {
      "className": "org.postgresql.test.jdbc3.StringTypeParameterTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc3.StringTypeParameterTest#testParameterUnspecified"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 1
    },
    {
      "className": "org.postgresql.test.jdbc2.optional.PoolingDataSourceTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc2.optional.PoolingDataSourceTest#testDdlOverConnection",
        "org.postgresql.test.jdbc2.optional.PoolingDataSourceTest#testGetConnection",
        "org.postgresql.test.jdbc2.optional.PoolingDataSourceTest#testDoubleConnectionClose",
        "org.postgresql.test.jdbc2.optional.PoolingDataSourceTest#testJndi",
        "org.postgresql.test.jdbc2.optional.PoolingDataSourceTest#testCantReuseName",
        "org.postgresql.test.jdbc2.optional.PoolingDataSourceTest#testUseConnection",
        "org.postgresql.test.jdbc2.optional.PoolingDataSourceTest#testPGConnection",
        "org.postgresql.test.jdbc2.optional.PoolingDataSourceTest#testNotPooledConnection",
        "org.postgresql.test.jdbc2.optional.PoolingDataSourceTest#testDoubleStatementClose",
        "org.postgresql.test.jdbc2.optional.PoolingDataSourceTest#testConnectionObjectMethods",
        "org.postgresql.test.jdbc2.optional.PoolingDataSourceTest#testCreateDataSource",
        "org.postgresql.test.jdbc2.optional.PoolingDataSourceTest#testStatementObjectMethods"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 24
    },
    {
      "className": "org.postgresql.test.xa.XATestSuite",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.xa.XATestSuite#initializationError"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 1
    },
    {
      "className": "org.postgresql.test.jdbc42.SimpleJdbc42Test",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc42.SimpleJdbc42Test#testSupportsRefCursors"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 1
    },
    {
      "className": "org.postgresql.test.jdbc2.optional.SimpleDataSourceTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc2.optional.SimpleDataSourceTest#testNotPooledConnection",
        "org.postgresql.test.jdbc2.optional.SimpleDataSourceTest#testPGConnection",
        "org.postgresql.test.jdbc2.optional.SimpleDataSourceTest#testDdlOverConnection",
        "org.postgresql.test.jdbc2.optional.SimpleDataSourceTest#testUseConnection",
        "org.postgresql.test.jdbc2.optional.SimpleDataSourceTest#testGetConnection",
        "org.postgresql.test.jdbc2.optional.SimpleDataSourceTest#testJndi",
        "org.postgresql.test.jdbc2.optional.SimpleDataSourceTest#testCreateDataSource"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 14
    },
    {
      "className": "org.postgresql.test.jdbc3.DatabaseMetaDataTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc3.DatabaseMetaDataTest#testGetColumnsForDomain"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 2
    },
    {
      "className": "org.postgresql.test.jdbc42.CustomizeDefaultFetchSizeTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc42.CustomizeDefaultFetchSizeTest#testSetPredefineDefaultFetchSizeOnPreparedStatement",
        "org.postgresql.test.jdbc42.CustomizeDefaultFetchSizeTest#testSetPredefineDefaultFetchSizeOnStatement"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 2
    },
    {
      "className": "org.postgresql.test.jdbc4.jdbc41.GetObjectTest",
      "failingMethods": [
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetMoney"
      ],
      "erroringMethods": [
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetSerial",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetInet6Address",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetInterval",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetDoubleNull",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetBox",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetArray",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetBigDecimal",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetCircle",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetBooleanNull",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetTime",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetPolygon",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetBoolean",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetPath",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetFloat",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetBlob",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetTimestampWithTimeZone",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetDouble",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetLongNull",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetPoint",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetIntegerNull",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetLong",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetClob",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetDate",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetLine",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetInteger",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetTimestamp",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetString",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetXml",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetInet4Address",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetFloatNull",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetInetAddressNull",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetLineseg",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetCalendar",
        "org.postgresql.test.jdbc4.jdbc41.GetObjectTest#testGetUuid"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "skipped",
          "failureDetail": "skipped",
          "isError": false
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        }
      ],
      "nbFailures": 1,
      "nbErrors": 68
    },
    {
      "className": "org.postgresql.test.jdbc4.jdbc41.AbortTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc4.jdbc41.AbortTest#testAbortOnClosedConnection",
        "org.postgresql.test.jdbc4.jdbc41.AbortTest#testAbort"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 2
    },
    {
      "className": "org.postgresql.test.jdbc42.PreparedStatementTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc42.PreparedStatementTest#testTimeTzSetNull",
        "org.postgresql.test.jdbc42.PreparedStatementTest#testTimestampTzSetNull"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 2
    },
    {
      "className": "org.postgresql.test.jdbc2.optional.ConnectionPoolTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc2.optional.ConnectionPoolTest#testJndi",
        "org.postgresql.test.jdbc2.optional.ConnectionPoolTest#testDdlOverConnection",
        "org.postgresql.test.jdbc2.optional.ConnectionPoolTest#testPoolReuse",
        "org.postgresql.test.jdbc2.optional.ConnectionPoolTest#testBackendIsClosed",
        "org.postgresql.test.jdbc2.optional.ConnectionPoolTest#testCloseEvent",
        "org.postgresql.test.jdbc2.optional.ConnectionPoolTest#testPoolCloseOldWrapper",
        "org.postgresql.test.jdbc2.optional.ConnectionPoolTest#testPreparedStatementConnection",
        "org.postgresql.test.jdbc2.optional.ConnectionPoolTest#testGetConnection",
        "org.postgresql.test.jdbc2.optional.ConnectionPoolTest#testCreateDataSource",
        "org.postgresql.test.jdbc2.optional.ConnectionPoolTest#testStatementsProxyPGStatement",
        "org.postgresql.test.jdbc2.optional.ConnectionPoolTest#testNoCloseEvent",
        "org.postgresql.test.jdbc2.optional.ConnectionPoolTest#testUseConnection",
        "org.postgresql.test.jdbc2.optional.ConnectionPoolTest#testNotPooledConnection",
        "org.postgresql.test.jdbc2.optional.ConnectionPoolTest#testPoolNewWrapper",
        "org.postgresql.test.jdbc2.optional.ConnectionPoolTest#testAutomaticCloseEvent",
        "org.postgresql.test.jdbc2.optional.ConnectionPoolTest#testStatementConnection",
        "org.postgresql.test.jdbc2.optional.ConnectionPoolTest#testIsClosed",
        "org.postgresql.test.jdbc2.optional.ConnectionPoolTest#testCallableStatementConnection",
        "org.postgresql.test.jdbc2.optional.ConnectionPoolTest#testInlineCloseEvent",
        "org.postgresql.test.jdbc2.optional.ConnectionPoolTest#testSerializable",
        "org.postgresql.test.jdbc2.optional.ConnectionPoolTest#testPGConnection",
        "org.postgresql.test.jdbc2.optional.ConnectionPoolTest#testStatementProxy"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 22
    },
    {
      "className": "org.postgresql.test.jdbc3.ResultSetTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc3.ResultSetTest#testHoldableResultSet"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 2
    },
    {
      "className": "org.postgresql.test.jdbc42.GetObject310BinaryTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc42.GetObject310BinaryTest#testGetLocalTimeInvalidType",
        "org.postgresql.test.jdbc42.GetObject310BinaryTest#testGetLocalDateTime",
        "org.postgresql.test.jdbc42.GetObject310BinaryTest#testGetTimestampWithTimeZone",
        "org.postgresql.test.jdbc42.GetObject310BinaryTest#testGetLocalTime",
        "org.postgresql.test.jdbc42.GetObject310BinaryTest#testGetLocalTimeNull",
        "org.postgresql.test.jdbc42.GetObject310BinaryTest#testGetLocalDate"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 6
    },
    {
      "className": "org.postgresql.test.jdbc42.Jdbc42CallableStatementTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc42.Jdbc42CallableStatementTest#testGetResultSetWithoutArg",
        "org.postgresql.test.jdbc42.Jdbc42CallableStatementTest#testGetResultSetWithoutArgUnsupportedConversion"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 4
    },
    {
      "className": "org.postgresql.replication.ReplicationTestSuite",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.replication.ReplicationTestSuite#org.postgresql.replication.ReplicationTestSuite"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 1
    },
    {
      "className": "org.postgresql.test.socketfactory.SocketFactoryTestSuite",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.socketfactory.SocketFactoryTestSuite#testDatabaseMetaData"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 1
    },
    {
      "className": "org.postgresql.test.jdbc3.Jdbc3BlobTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc3.Jdbc3BlobTest#testAllBytes",
        "org.postgresql.test.jdbc3.Jdbc3BlobTest#test1ByteOffset",
        "org.postgresql.test.jdbc3.Jdbc3BlobTest#test1ByteStream",
        "org.postgresql.test.jdbc3.Jdbc3BlobTest#testManyBytesOffsetStream",
        "org.postgresql.test.jdbc3.Jdbc3BlobTest#testAllBytesStream",
        "org.postgresql.test.jdbc3.Jdbc3BlobTest#test1ByteOffsetStream",
        "org.postgresql.test.jdbc3.Jdbc3BlobTest#testManyBytesOffset",
        "org.postgresql.test.jdbc3.Jdbc3BlobTest#testTruncate",
        "org.postgresql.test.jdbc3.Jdbc3BlobTest#testPattern",
        "org.postgresql.test.jdbc3.Jdbc3BlobTest#testManyBytesStream",
        "org.postgresql.test.jdbc3.Jdbc3BlobTest#testManyBytes",
        "org.postgresql.test.jdbc3.Jdbc3BlobTest#test1Byte"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 24
    },
    {
      "className": "org.postgresql.test.jdbc2.optional.SimpleDataSourceWithUrlTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc2.optional.SimpleDataSourceWithUrlTest#testCreateDataSource",
        "org.postgresql.test.jdbc2.optional.SimpleDataSourceWithUrlTest#testPGConnection",
        "org.postgresql.test.jdbc2.optional.SimpleDataSourceWithUrlTest#testUseConnection",
        "org.postgresql.test.jdbc2.optional.SimpleDataSourceWithUrlTest#testDdlOverConnection",
        "org.postgresql.test.jdbc2.optional.SimpleDataSourceWithUrlTest#testJndi",
        "org.postgresql.test.jdbc2.optional.SimpleDataSourceWithUrlTest#testNotPooledConnection",
        "org.postgresql.test.jdbc2.optional.SimpleDataSourceWithUrlTest#testGetConnection"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 14
    },
    {
      "className": "org.postgresql.test.extensions.ExtensionsTestSuite",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.extensions.ExtensionsTestSuite#initializationError"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 1
    },
    {
      "className": "org.postgresql.test.jdbc2.Jdbc2TestSuite",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc2.Jdbc2TestSuite#initializationError"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 1
    },
    {
      "className": "org.postgresql.test.jdbc42.SetObject310Test",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc42.SetObject310Test#testSetLocalDateTime",
        "org.postgresql.test.jdbc42.SetObject310Test#testSetLocalTimeWithType",
        "org.postgresql.test.jdbc42.SetObject310Test#testSetOffsetDateTime",
        "org.postgresql.test.jdbc42.SetObject310Test#testSetLocalDateWithoutType",
        "org.postgresql.test.jdbc42.SetObject310Test#testSetLocalTimeWithoutType",
        "org.postgresql.test.jdbc42.SetObject310Test#testSetLocalDateWithType",
        "org.postgresql.test.jdbc42.SetObject310Test#testSetLocalTimeAndReadBack",
        "org.postgresql.test.jdbc42.SetObject310Test#testSetLocalDateTimeBc"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 16
    },
    {
      "className": "org.postgresql.test.jdbc4.jdbc41.CloseOnCompletionTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc4.jdbc41.CloseOnCompletionTest#testMultipleResultSet",
        "org.postgresql.test.jdbc4.jdbc41.CloseOnCompletionTest#testNoResultSet",
        "org.postgresql.test.jdbc4.jdbc41.CloseOnCompletionTest#testSingleResultSet",
        "org.postgresql.test.jdbc4.jdbc41.CloseOnCompletionTest#testWithoutCloseOnCompletion"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 8
    },
    {
      "className": "org.postgresql.test.jdbc2.optional.CaseOptimiserDataSourceTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc2.optional.CaseOptimiserDataSourceTest#testDataSourceDisabledSanitiserPropertySucceeds"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 2
    },
    {
      "className": "org.postgresql.test.jdbc3.TypesTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc3.TypesTest#testPreparedByte",
        "org.postgresql.test.jdbc3.TypesTest#testUnknownType",
        "org.postgresql.test.jdbc3.TypesTest#testPreparedBoolean",
        "org.postgresql.test.jdbc3.TypesTest#testCallableBoolean"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 8
    },
    {
      "className": "org.postgresql.test.jdbc3.SendRecvBufferSizeTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc3.SendRecvBufferSizeTest#testSelect"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 2
    },
    {
      "className": "org.postgresql.test.jdbc3.ParameterMetaDataTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc3.ParameterMetaDataTest#testParameterMD",
        "org.postgresql.test.jdbc3.ParameterMetaDataTest#testTypeChangeWithUnknown",
        "org.postgresql.test.jdbc3.ParameterMetaDataTest#testMultiStatement",
        "org.postgresql.test.jdbc3.ParameterMetaDataTest#testFailsOnBadIndex"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 8
    },
    {
      "className": "org.postgresql.test.jdbc4.jdbc41.SchemaTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc4.jdbc41.SchemaTest#testSearchPathPreparedStatementAutoCommitFalse",
        "org.postgresql.test.jdbc4.jdbc41.SchemaTest#testMultipleSearchPath",
        "org.postgresql.test.jdbc4.jdbc41.SchemaTest#testSchemaInProperties",
        "org.postgresql.test.jdbc4.jdbc41.SchemaTest#testSearchPathPreparedStatementAutoCommitTrue",
        "org.postgresql.test.jdbc4.jdbc41.SchemaTest#testGetSetSchema",
        "org.postgresql.test.jdbc4.jdbc41.SchemaTest#testSchemaPath$User",
        "org.postgresql.test.jdbc4.jdbc41.SchemaTest#testSearchPathPreparedStatement",
        "org.postgresql.test.jdbc4.jdbc41.SchemaTest#testUsingSchema"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 16
    },
    {
      "className": "org.postgresql.test.jdbc42.GetObject310InfinityTests",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc42.GetObject310InfinityTests#test[binary \u003d REGULAR, expr \u003d -infinity, pgType \u003d timestamp, klass \u003d class java.time.LocalDateTime]",
        "org.postgresql.test.jdbc42.GetObject310InfinityTests#test[binary \u003d FORCE, expr \u003d -infinity, pgType \u003d timestamp, klass \u003d class java.time.OffsetDateTime]",
        "org.postgresql.test.jdbc42.GetObject310InfinityTests#test[binary \u003d REGULAR, expr \u003d -infinity, pgType \u003d timestamp, klass \u003d class java.time.OffsetDateTime]",
        "org.postgresql.test.jdbc42.GetObject310InfinityTests#test[binary \u003d REGULAR, expr \u003d -infinity, pgType \u003d timestamp with time zone, klass \u003d class java.time.OffsetDateTime]",
        "org.postgresql.test.jdbc42.GetObject310InfinityTests#test[binary \u003d REGULAR, expr \u003d infinity, pgType \u003d date, klass \u003d class java.time.LocalDate]",
        "org.postgresql.test.jdbc42.GetObject310InfinityTests#test[binary \u003d FORCE, expr \u003d infinity, pgType \u003d timestamp, klass \u003d class java.time.OffsetDateTime]",
        "org.postgresql.test.jdbc42.GetObject310InfinityTests#test[binary \u003d FORCE, expr \u003d infinity, pgType \u003d timestamp with time zone, klass \u003d class java.time.OffsetDateTime]",
        "org.postgresql.test.jdbc42.GetObject310InfinityTests#test[binary \u003d REGULAR, expr \u003d -infinity, pgType \u003d date, klass \u003d class java.time.LocalDate]",
        "org.postgresql.test.jdbc42.GetObject310InfinityTests#test[binary \u003d FORCE, expr \u003d -infinity, pgType \u003d date, klass \u003d class java.time.LocalDate]",
        "org.postgresql.test.jdbc42.GetObject310InfinityTests#test[binary \u003d FORCE, expr \u003d infinity, pgType \u003d timestamp, klass \u003d class java.time.LocalDateTime]",
        "org.postgresql.test.jdbc42.GetObject310InfinityTests#test[binary \u003d REGULAR, expr \u003d infinity, pgType \u003d timestamp, klass \u003d class java.time.LocalDateTime]",
        "org.postgresql.test.jdbc42.GetObject310InfinityTests#test[binary \u003d REGULAR, expr \u003d infinity, pgType \u003d timestamp with time zone, klass \u003d class java.time.OffsetDateTime]",
        "org.postgresql.test.jdbc42.GetObject310InfinityTests#test[binary \u003d FORCE, expr \u003d -infinity, pgType \u003d timestamp with time zone, klass \u003d class java.time.OffsetDateTime]",
        "org.postgresql.test.jdbc42.GetObject310InfinityTests#test[binary \u003d FORCE, expr \u003d -infinity, pgType \u003d timestamp, klass \u003d class java.time.LocalDateTime]",
        "org.postgresql.test.jdbc42.GetObject310InfinityTests#test[binary \u003d REGULAR, expr \u003d infinity, pgType \u003d timestamp, klass \u003d class java.time.OffsetDateTime]",
        "org.postgresql.test.jdbc42.GetObject310InfinityTests#test[binary \u003d FORCE, expr \u003d infinity, pgType \u003d date, klass \u003d class java.time.LocalDate]"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 16
    },
    {
      "className": "org.postgresql.test.jdbc3.Jdbc3SavepointTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc3.Jdbc3SavepointTest#testRollingBackToInvalidSavepointFails",
        "org.postgresql.test.jdbc3.Jdbc3SavepointTest#testContinueAfterError",
        "org.postgresql.test.jdbc3.Jdbc3SavepointTest#testReleaseSavepoint",
        "org.postgresql.test.jdbc3.Jdbc3SavepointTest#testCantMixSavepointTypes",
        "org.postgresql.test.jdbc3.Jdbc3SavepointTest#testComplicatedSavepointName",
        "org.postgresql.test.jdbc3.Jdbc3SavepointTest#testRollingBackToSavepoints",
        "org.postgresql.test.jdbc3.Jdbc3SavepointTest#testRollbackMultipleTimes",
        "org.postgresql.test.jdbc3.Jdbc3SavepointTest#testGlobalRollbackWorks",
        "org.postgresql.test.jdbc3.Jdbc3SavepointTest#testAutoCommitFails"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 18
    },
    {
      "className": "org.postgresql.test.jdbc2.AutoRollbackTestSuite",
      "failingMethods": [],
      "erroringMethods": [
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[32: autorollback(autoSave\u003dALWAYS, autoCommit\u003dYES, failMode\u003dSELECT, continueMode\u003dCOMMIT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[44: autorollback(autoSave\u003dALWAYS, autoCommit\u003dYES, failMode\u003dDISCARD, continueMode\u003dIS_VALID, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[72: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dYES, failMode\u003dDEALLOCATE, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[30: autorollback(autoSave\u003dNEVER, autoCommit\u003dNO, failMode\u003dINSERT_BATCH, continueMode\u003dIS_VALID, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[93: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dNO, failMode\u003dINSERT_BATCH, continueMode\u003dCOMMIT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[18: autorollback(autoSave\u003dNEVER, autoCommit\u003dYES, failMode\u003dINSERT_BATCH, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[8: autorollback(autoSave\u003dNEVER, autoCommit\u003dYES, failMode\u003dDEALLOCATE, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[47: autorollback(autoSave\u003dALWAYS, autoCommit\u003dYES, failMode\u003dDISCARD, continueMode\u003dSELECT, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[70: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dYES, failMode\u003dDEALLOCATE, continueMode\u003dIS_VALID, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[61: autorollback(autoSave\u003dALWAYS, autoCommit\u003dNO, failMode\u003dINSERT_BATCH, continueMode\u003dCOMMIT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[3: autorollback(autoSave\u003dNEVER, autoCommit\u003dYES, failMode\u003dALTER, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[26: autorollback(autoSave\u003dNEVER, autoCommit\u003dNO, failMode\u003dDEALLOCATE, continueMode\u003dIS_VALID, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[51: autorollback(autoSave\u003dALWAYS, autoCommit\u003dNO, failMode\u003dSELECT, continueMode\u003dCOMMIT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[87: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dNO, failMode\u003dDEALLOCATE, continueMode\u003dCOMMIT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[65: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dYES, failMode\u003dSELECT, continueMode\u003dIS_VALID, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[92: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dNO, failMode\u003dDEALLOCATE, continueMode\u003dSELECT, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[50: autorollback(autoSave\u003dALWAYS, autoCommit\u003dYES, failMode\u003dINSERT_BATCH, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[41: autorollback(autoSave\u003dALWAYS, autoCommit\u003dYES, failMode\u003dDEALLOCATE, continueMode\u003dSELECT, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[64: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dYES, failMode\u003dSELECT, continueMode\u003dCOMMIT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[14: autorollback(autoSave\u003dNEVER, autoCommit\u003dYES, failMode\u003dDISCARD, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[24: autorollback(autoSave\u003dNEVER, autoCommit\u003dNO, failMode\u003dDEALLOCATE, continueMode\u003dCOMMIT, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[86: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dNO, failMode\u003dALTER, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[1: autorollback(autoSave\u003dNEVER, autoCommit\u003dYES, failMode\u003dSELECT, continueMode\u003dIS_VALID, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[82: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dYES, failMode\u003dINSERT_BATCH, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[85: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dNO, failMode\u003dSELECT, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[62: autorollback(autoSave\u003dALWAYS, autoCommit\u003dNO, failMode\u003dINSERT_BATCH, continueMode\u003dIS_VALID, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[23: autorollback(autoSave\u003dNEVER, autoCommit\u003dNO, failMode\u003dDEALLOCATE, continueMode\u003dCOMMIT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[88: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dNO, failMode\u003dDEALLOCATE, continueMode\u003dCOMMIT, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[25: autorollback(autoSave\u003dNEVER, autoCommit\u003dNO, failMode\u003dDEALLOCATE, continueMode\u003dIS_VALID, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[54: autorollback(autoSave\u003dALWAYS, autoCommit\u003dNO, failMode\u003dALTER, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[20: autorollback(autoSave\u003dNEVER, autoCommit\u003dNO, failMode\u003dSELECT, continueMode\u003dIS_VALID, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[10: autorollback(autoSave\u003dNEVER, autoCommit\u003dYES, failMode\u003dDISCARD, continueMode\u003dCOMMIT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[57: autorollback(autoSave\u003dALWAYS, autoCommit\u003dNO, failMode\u003dDEALLOCATE, continueMode\u003dIS_VALID, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[90: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dNO, failMode\u003dDEALLOCATE, continueMode\u003dIS_VALID, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[31: autorollback(autoSave\u003dNEVER, autoCommit\u003dNO, failMode\u003dINSERT_BATCH, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[34: autorollback(autoSave\u003dALWAYS, autoCommit\u003dYES, failMode\u003dSELECT, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[36: autorollback(autoSave\u003dALWAYS, autoCommit\u003dYES, failMode\u003dDEALLOCATE, continueMode\u003dCOMMIT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[73: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dYES, failMode\u003dDEALLOCATE, continueMode\u003dSELECT, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[71: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dYES, failMode\u003dDEALLOCATE, continueMode\u003dIS_VALID, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[74: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dYES, failMode\u003dDISCARD, continueMode\u003dCOMMIT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[29: autorollback(autoSave\u003dNEVER, autoCommit\u003dNO, failMode\u003dINSERT_BATCH, continueMode\u003dCOMMIT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[11: autorollback(autoSave\u003dNEVER, autoCommit\u003dYES, failMode\u003dDISCARD, continueMode\u003dCOMMIT, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[81: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dYES, failMode\u003dINSERT_BATCH, continueMode\u003dIS_VALID, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[94: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dNO, failMode\u003dINSERT_BATCH, continueMode\u003dIS_VALID, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[0: autorollback(autoSave\u003dNEVER, autoCommit\u003dYES, failMode\u003dSELECT, continueMode\u003dCOMMIT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[35: autorollback(autoSave\u003dALWAYS, autoCommit\u003dYES, failMode\u003dALTER, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[69: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dYES, failMode\u003dDEALLOCATE, continueMode\u003dCOMMIT, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[52: autorollback(autoSave\u003dALWAYS, autoCommit\u003dNO, failMode\u003dSELECT, continueMode\u003dIS_VALID, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[75: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dYES, failMode\u003dDISCARD, continueMode\u003dCOMMIT, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[40: autorollback(autoSave\u003dALWAYS, autoCommit\u003dYES, failMode\u003dDEALLOCATE, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[22: autorollback(autoSave\u003dNEVER, autoCommit\u003dNO, failMode\u003dALTER, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[48: autorollback(autoSave\u003dALWAYS, autoCommit\u003dYES, failMode\u003dINSERT_BATCH, continueMode\u003dCOMMIT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[39: autorollback(autoSave\u003dALWAYS, autoCommit\u003dYES, failMode\u003dDEALLOCATE, continueMode\u003dIS_VALID, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[91: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dNO, failMode\u003dDEALLOCATE, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[37: autorollback(autoSave\u003dALWAYS, autoCommit\u003dYES, failMode\u003dDEALLOCATE, continueMode\u003dCOMMIT, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[49: autorollback(autoSave\u003dALWAYS, autoCommit\u003dYES, failMode\u003dINSERT_BATCH, continueMode\u003dIS_VALID, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[58: autorollback(autoSave\u003dALWAYS, autoCommit\u003dNO, failMode\u003dDEALLOCATE, continueMode\u003dIS_VALID, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[33: autorollback(autoSave\u003dALWAYS, autoCommit\u003dYES, failMode\u003dSELECT, continueMode\u003dIS_VALID, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[78: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dYES, failMode\u003dDISCARD, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[2: autorollback(autoSave\u003dNEVER, autoCommit\u003dYES, failMode\u003dSELECT, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[38: autorollback(autoSave\u003dALWAYS, autoCommit\u003dYES, failMode\u003dDEALLOCATE, continueMode\u003dIS_VALID, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[27: autorollback(autoSave\u003dNEVER, autoCommit\u003dNO, failMode\u003dDEALLOCATE, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[13: autorollback(autoSave\u003dNEVER, autoCommit\u003dYES, failMode\u003dDISCARD, continueMode\u003dIS_VALID, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[63: autorollback(autoSave\u003dALWAYS, autoCommit\u003dNO, failMode\u003dINSERT_BATCH, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[17: autorollback(autoSave\u003dNEVER, autoCommit\u003dYES, failMode\u003dINSERT_BATCH, continueMode\u003dIS_VALID, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[16: autorollback(autoSave\u003dNEVER, autoCommit\u003dYES, failMode\u003dINSERT_BATCH, continueMode\u003dCOMMIT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[46: autorollback(autoSave\u003dALWAYS, autoCommit\u003dYES, failMode\u003dDISCARD, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[83: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dNO, failMode\u003dSELECT, continueMode\u003dCOMMIT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[6: autorollback(autoSave\u003dNEVER, autoCommit\u003dYES, failMode\u003dDEALLOCATE, continueMode\u003dIS_VALID, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[66: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dYES, failMode\u003dSELECT, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[76: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dYES, failMode\u003dDISCARD, continueMode\u003dIS_VALID, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[68: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dYES, failMode\u003dDEALLOCATE, continueMode\u003dCOMMIT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[80: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dYES, failMode\u003dINSERT_BATCH, continueMode\u003dCOMMIT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[42: autorollback(autoSave\u003dALWAYS, autoCommit\u003dYES, failMode\u003dDISCARD, continueMode\u003dCOMMIT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[45: autorollback(autoSave\u003dALWAYS, autoCommit\u003dYES, failMode\u003dDISCARD, continueMode\u003dIS_VALID, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[60: autorollback(autoSave\u003dALWAYS, autoCommit\u003dNO, failMode\u003dDEALLOCATE, continueMode\u003dSELECT, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[19: autorollback(autoSave\u003dNEVER, autoCommit\u003dNO, failMode\u003dSELECT, continueMode\u003dCOMMIT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[95: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dNO, failMode\u003dINSERT_BATCH, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[7: autorollback(autoSave\u003dNEVER, autoCommit\u003dYES, failMode\u003dDEALLOCATE, continueMode\u003dIS_VALID, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[12: autorollback(autoSave\u003dNEVER, autoCommit\u003dYES, failMode\u003dDISCARD, continueMode\u003dIS_VALID, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[15: autorollback(autoSave\u003dNEVER, autoCommit\u003dYES, failMode\u003dDISCARD, continueMode\u003dSELECT, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[84: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dNO, failMode\u003dSELECT, continueMode\u003dIS_VALID, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[21: autorollback(autoSave\u003dNEVER, autoCommit\u003dNO, failMode\u003dSELECT, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[55: autorollback(autoSave\u003dALWAYS, autoCommit\u003dNO, failMode\u003dDEALLOCATE, continueMode\u003dCOMMIT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[59: autorollback(autoSave\u003dALWAYS, autoCommit\u003dNO, failMode\u003dDEALLOCATE, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[28: autorollback(autoSave\u003dNEVER, autoCommit\u003dNO, failMode\u003dDEALLOCATE, continueMode\u003dSELECT, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[89: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dNO, failMode\u003dDEALLOCATE, continueMode\u003dIS_VALID, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[67: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dYES, failMode\u003dALTER, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[4: autorollback(autoSave\u003dNEVER, autoCommit\u003dYES, failMode\u003dDEALLOCATE, continueMode\u003dCOMMIT, flushOnDeallocate\u003dtrue)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[56: autorollback(autoSave\u003dALWAYS, autoCommit\u003dNO, failMode\u003dDEALLOCATE, continueMode\u003dCOMMIT, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[77: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dYES, failMode\u003dDISCARD, continueMode\u003dIS_VALID, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[9: autorollback(autoSave\u003dNEVER, autoCommit\u003dYES, failMode\u003dDEALLOCATE, continueMode\u003dSELECT, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[79: autorollback(autoSave\u003dCONSERVATIVE, autoCommit\u003dYES, failMode\u003dDISCARD, continueMode\u003dSELECT, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[43: autorollback(autoSave\u003dALWAYS, autoCommit\u003dYES, failMode\u003dDISCARD, continueMode\u003dCOMMIT, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[5: autorollback(autoSave\u003dNEVER, autoCommit\u003dYES, failMode\u003dDEALLOCATE, continueMode\u003dCOMMIT, flushOnDeallocate\u003dfalse)]",
        "org.postgresql.test.jdbc2.AutoRollbackTestSuite#run[53: autorollback(autoSave\u003dALWAYS, autoCommit\u003dNO, failMode\u003dSELECT, continueMode\u003dSELECT, flushOnDeallocate\u003dtrue)]"
      ],
      "failures": [
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "failureDetail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 96
    }
  ],
  "step-durations": {
    "CheckoutBuild": 3,
    "": 0,
    "CloneRepository": 8,
    "ResolveDependency": 14,
    "TestProject": 9,
    "BuildProject": 27,
    "SquashRepository": 2
  },
  "workspace": "./workspace",
  "pr-base-commit-id-url": "https://github.com/pgjdbc/pgjdbc/commit/2958cc22a6a00609bfbb6eb17d4e401dfe433123",
  "failingModule": "/root/workspace/pgjdbc/pgjdbc/222601706/pgjdbc"
}